### ISSUE TITLE
build instruction

### ISSUE THREAD

**Issue by amirmasud** [aliyun/elasticsearch-repository-oss#5]
Hi! 
I wanted to know the build instruction of the project.  (with mvn or if there is any missing gradlew available)
when I run `mvn clean install` got 3 errors
Also your [v.5.5.3 release](https://github.com/zhichen/elasticsearch-repository-oss/archive/v5.5.3.zip) file differs from your `elasticsearch-repository-oss-release` directory on master branch. 
(`elasticsearch-repository-oss-5.5.3.jar` and `plugin-security.policy` differ)

the generated release zip file with `mvn install -DskipTests` doesn't work with elasticsearch too.

Thanks in advance :pray:

**Comment by amirmasud** [comment]
It seems tests will pass and build will be completed when `-Dtests.security.manager=false` flag is provided :thinking: 

but after installing built plugin on elasticsearch, registering a snapshot repository gets this error:

`Unable to execute HTTP request: access denied ("java.net.SocketPermission" "an_IP:80" "connect,resolve")`

(there is no such error when using your v5.5.3 release zip file)

**Comment by anjia0532** [comment]
ping @amirmasud 
ref https://github.com/zhichen/elasticsearch-repository-oss/pull/6
or my branch
https://github.com/anjia0532/elasticsearch-repository-oss#%E4%BF%AE%E6%94%B9es-config%E7%9B%AE%E5%BD%95%E4%B8%8B%E7%9A%84jvmoptions%E6%96%87%E4%BB%B6%E6%9C%80%E5%90%8E%E4%B8%80%E8%A1%8C%E6%B7%BB%E5%8A%A0

**Comment by anjia0532** [comment]
Or modify `OssBlobStore.java`
```java
    /**
     * Return true if the given bucket exists
     *
     * @param bucketName name of the bucket
     * @return true if the bucket exists, false otherwise
     */
    boolean doesBucketExist(String bucketName) throws IOException{
        return doPrivileged(() -> this.client.doesBucketExist(bucketName));
    }
```
modify `plugin-security.policy`

```java
grant {
    permission java.net.SocketPermission "*", "connect,resolve";
    permission java.lang.RuntimePermission "getClassLoader";
    permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
    permission java.lang.RuntimePermission "accessDeclaredMembers";
};
```
to fix this issues.

**Comment by zhichen** [comment]
已经发布了6.3.2版本，可以修改版本号支持6.1.3
